0-run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,19 +1,6 @@
 #!/bin/bash
 
-#check if environment variable is set
+[ -z "$PYFILE" ] && { echo "Error: PYFILE environment variable is not set."; exit 1; }
+[ ! -f "$PYFILE" ] && { echo "Error: Python file '$PYFILE' not found."; exit 1; }
+python "$PYFILE"
 
-if [ -z "$PYFILE" ]; then
-	echo"Error: PYFILE environment variable not set"
-	
-	exit 1
-fi
-
-	#check if file exists
-	
-if [ ! -f "$PYFILE" ]; then
-	echo"Error: Python file $PYFILE not found"
-	exit 1
-fi
-
-#Run script
-python3 "$PYFILE"
